spring.application.name=Metropark 

# Standard JDBC Configuration 
spring.datasource.url=jdbc:postgresql://localhost:5432/metropark
spring.datasource.username=postgres
spring.datasource.password=21125@aaJV
spring.datasource.driver-class-name=org.postgresql.Driver

# Reactive R2DBC Configuration 
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/metropark
spring.r2dbc.username=postgres
spring.r2dbc.password=21125@aaJV

# --- ADD THE JOOQ DIALECT HERE ---
spring.jooq.sql-dialect=POSTGRES

# Logging
logging.level.root=INFO
logging.level.com.example.Metropark=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n
logging.file.name=logs/metropark.log