spring.application.name=Metropark 
# Standard JDBC Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/metropark_test
spring.datasource.username=postgres
spring.datasource.password=21125@aaJV
spring.datasource.driver-class-name=org.postgresql.Driver

# Reactive R2DBC Configuration
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/metropark_test
spring.r2dbc.username=postgres
spring.r2dbc.password=21125@aaJV